---

- name: Install development packages
  action: yum name='@development' state=latest

- name: Install need system libraries and tools
  yum: name={{ item }} state=latest
  with_items:
    - bash
    - bash-completion
    - openssl
    - openssl-devel
    - rng-tools
    - libxml2-devel
    - libjpeg
    - libjpeg-devel
    - bzip2-devel
    - freetype
    - freetype-devel
    - zlib-devel
    - postgresql-libs
    - sqlite-devel

- name: Install base packages
  yum: name={{ item }} state=latest
  with_items:
    - curl
    - htop
    - git

- name: IInstall Python System-level packages
  yum: name={{ item }} state=latest
  with_items:
    - python27
    - python27-devel
    - python-pip
    - python33
    - python-virtualenv
