---
- include: create_swap_file.yml
  when: base_create_swap_file
  tags: swap

- include: base-debian.yml
  when: ansible_os_family == 'Debian'
  tags:
   - packages
   - debian-base

- include: base-redhat.yml
  when: ansible_os_family == 'RedHat'
  tags:
   - packages
   - redhat-base
