---

# The name of the app. Should be a slug.
site_name: "appname"

# The user that will own all of the project files.
site_user: "{{site_name}}"

# The group that will be assigned to all of the project files.
shared_group: "worker"

# The database user the the app will use
db_user: "{{site_name}}"

# The database password that the app will use
db_password: "change_me"

# The database name that the app will use.
db_name: "{{site_name}}"

# The python binary to use.
python_version: "python3.5" # "python2.7" or "python3.4" or "python3.5"

# The git repo to checkout.
git_repo: "https://github.com/chicagopython/chipy.org.git"

# The branch to checkout
git_branch: "master"

# The top directory under which all project files should reside
top_dir: "/srv/"

sites_dir: "{{top_dir}}sites/"
sites_bin_dir: "{{top_dir}}bin/"
site_dir: "{{sites_dir}}{{site_name}}/"
htdocs_dir: "{{site_dir}}htdocs/"
htdocs_media_dir: "{{htdocs_dir}}media/"
htdocs_static_dir: "{{htdocs_dir}}static/"
site_log_dir: "{{site_dir}}log/"
site_run_dir: "{{site_dir}}run/"
site_etc_dir: "{{site_dir}}etc/"
site_nginx_dir: "{{site_etc_dir}}nginx/"
project_dir: "{{site_dir}}proj/"
virtualenvs_dir: "{{site_dir}}envs/"
virtualenv_dir_link: "{{virtualenvs_dir}}{{site_name}}"
virtualenv_dir: "{{virtualenv_dir_link}}/"

timezone: "America/Chicago"
application_runner: "uwsgi" # "uwsgi" or "gunicorn"

install_nginx: True
install_ntp: True
install_unattended_updates: True
install_postgis: True
install_postgres: True
install_postfix: True
install_mysql: True
install_redis: True
install_nrpe: True
install_timezone: True

base__create_swap_file: True

# define list of users here
users:
  - username: jjasinski
    name: Joe Jasinski
    groups:
      - "{{shared_group}}"
    uid: 1010
    password: '!'
    ssh_key:
      - "ssh-rsa AAAAA.... foo@machine"
    shell: /bin/bash
