---
site_name: "myappname"
site_user: "{{ site_name }}"
db_user: "{{ site_name }}"
db_password: "change_me"
db_name: "{{ site_name }}"
python_version: "python3.4" # "python2.7" or "python3.4"
sites_dir: "/srv/"
site_dir: "{{ sites_dir }}site/"
htdocs_dir: "{{ site_dir }}htdocs/"
site_log_dir: "{{ site_dir }}log/"
site_nginx_dir: "{{ site_dir }}etc/nginx/"
project_dir: "{{ site_dir }}proj/"
virtualenv_dir: "{{ site_dir }}venv/"

install_nginx: False
install_ntp: False
install_unattended_updates: False
install_postgis: False
install_postgres: False
install_mysql: True

# define list of users here
users:
  - username: jjasinski
    name: Joe Jasinski
    groups:
      - worker
    uid: 1010
    password: '!'
    ssh_key:
      - "ssh-rsa AAAAA.... foo@machine"
    shell: /bin/bash
