---

- name: Per-user group creation
  group: name="{{item.username}}" state="present"
  with_items: users
  tags:
    - users

- name: User creation
  user: name="{{item.username}}"
        group="{{item.username}}"
        groups="{{item.groups | join(',')}}"
        append=yes
        shell={{item.shell if item.shell is defined else users_default_shell}}
        password="{{item.password if item.password is defined else '!'}}"
        comment="{{item.name}}"
        uid="{{item.uid|default(omit)}}"
        createhome="{{'yes' if users_create_homedirs else 'no'}}"
  with_items: users
  tags:
    - users
