---

- name: Add deps
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present


- name: Adding Certbot repository
  apt_repository:
      repo: "{{ letsencrypt__apt_repository }}"
      state: present
      update_cache: yes

- name: Ensure Certbot packages are installed.
  apt:
    update_cache: "{{ update_apt_cache }}"
    state: latest
    name:
    - certbot
