---

- set_fact:
    sites_virtualenv_dir_version="{{virtualenvs_dir}}{{site_name}}-{{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"

- name: Creates sites directory
  file:
    path={{ sites_site_dir }}
    state=directory
    owner={{ site_user }}
    group={{ shared_group }}
    mode=2775

- name: Creates log directory
  file:
    path={{ sites_site_log_dir }}
    state=directory
    owner={{ site_user }}
    group={{ shared_group }}
    mode=2775

- name: Creates run directory
  file:
    path={{ sites_site_run_dir }}
    state=directory
    owner={{ site_user }}
    group={{ shared_group }}
    mode=2775


- include: setup_virtualenv.yml
  tags:
    - virtualenv

- include: setup_project.yml
  tags:
    - project

- name: Copy the venv script
  template:
    src=venv.j2
    dest=/etc/profile.d/venv
    owner=root
    group=root
    mode="u=rwx,g=rwx,o=rx"

- name: Fix ownership
  file:
    path={{ sites_site_dir }}
    owner={{ site_user }}
    group={{ shared_group }}
    recurse="yes"
