---

- name: Install NTP Deamon
  apt:
    update_cache: "{{ update_apt_cache }}"
    state: present
    name: ntp

- name: Start NTPD
  service:
    name: ntp
    state: started
    enabled: "{{ntp__enabled_on_startup}}"
