---
nagios_nrpe_server_service: nagios-nrpe-server
nagios_nrpe_server_plugins_dir: /usr/lib/nagios/plugins
nagios_nrpe_server_dir: /etc/nagios
nagios_nrpe_server_pid: /var/run/nagios/nrpe.pid
nagios_nrpe_server_user: nagios
nagios_nrpe_server_group: nagios
nagios_nrpe_server_port: 5666
nagios_nrpe_allowed_hosts: 127.0.0.1
nagios_nrpe_debug: 0
