---
- include: base-debian.yml
  when: ansible_os_family == 'Debian'
  tags:
    - packages
    - debian-base

- name: ensure postgres is enabled at boot
  service: name=postgresql enabled=yes

- name: Create database User
  become_user: postgres
  postgresql_user:
    name={{ postgres_db_user }}
    password={{ postgres_db_password }}

- name: Create database
  become_user: postgres
  postgresql_db:
    name={{ postgres_db_name }}
    owner={{ postgres_db_user }}
    encoding='UTF-8'
    lc_collate='en_US.UTF-8'
    lc_ctype='en_US.UTF-8'
    state=present

- name: ensure user does not have unnecessary privilege
  become_user: postgres
  postgresql_user:
    name={{postgres_db_user}}
    role_attr_flags=NOSUPERUSER,NOCREATEDB
