---

# - include: install_facts.yml
#   when: postgres__install_facts

- name: Load OS-Specific Tasks
  include: "{{ item }}"
  with_first_found:
   - "os-{{ ansible_distribution|lower }}-{{ ansible_distribution_release }}.yml"
   - "os-{{ ansible_distribution|lower }}.yml"
   - "os-{{ ansible_os_family|lower }}.yml"
   - "os-default.yml"

# - include_vars: "{{ item }}"
#   with_first_found:
#    - "os-vars-{{ ansible_distribution|lower }}-{{ ansible_distribution_release }}.yml"
#    - "os-vars-{{ ansible_distribution|lower }}.yml"
#    - "os-vars-{{ ansible_os_family }}.yml"
#    - "os-vars-default.yml"
