---

- name: Install Postgresql
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=latest
  with_items:
    - postgresql
    - postgresql-contrib
    - python-psycopg2
  tags:
    - packages
    - debian-base
