---

- name: Install Postgresql
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=latest
  with_items:
    - postgresql
    - postgresql-contrib
    - python-psycopg2

- name: Create database User
  become_user: postgres
  postgresql_user:
    name={{ postgres_db_user }}
    password={{ postgres_db_password }}

- name: Create database
  become_user: postgres
  postgresql_db:
    name={{ postgres_db_name }}
    owner={{ postgres_db_user }}
    encoding='UTF-8'
    lc_collate='en_US.UTF-8'
    lc_ctype='en_US.UTF-8'
    state=present
