---

- name: Ensure MySQL packages are installed.
  apt:
    update_cache: "{{ update_apt_cache }}"
    state: latest
    name:
    - mysql-common
    - mysql-server
    - libmysqlclient-dev


- name: Python3 mysql dependency
  apt:
    update_cache: "{{ update_apt_cache }}"
    state: latest
    name:
    - python3-dev
    - python3-pip

