---
- block:
    - name: Checkout git repo
      git: repo={{ django__git_repo }}
         version={{ django__git_branch }}
         dest={{ django__app_dir }}
         remote={{ django__remote_name }}
         accept_hostkey=yes
         force=yes
         recursive=no
      become: yes
      become_user: "{{ site_user }}"

    - file:
        path={{ django__app_dir }}
        state=directory
        recurse=yes
        mode=g+w

    - pip:
        requirements={{ django__requirements }}
        virtualenv={{ django__virtualenv_dir }}
        umask=0002
      become: yes
      become_user: "{{ site_user }}"
      ignore_errors: yes

    - django_manage: >
        command=collectstatic
        app_path={{ django__app_dir }}
        settings={{ django__settings }}
        virtualenv={{ django__virtualenv_dir }}
      become: yes
      become_user: "{{ site_user }}"
      ignore_errors: yes
  rescue:
    - debug: msg="environment checkout failed"
