---

- debug: msg="Vars path {{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"

- include_vars: "{{ item }}"
  with_first_found:
   - "os-{{ ansible_distribution|lower }}-{{ ansible_distribution_release }}.yml"
   - "os-{{ ansible_distribution|lower }}.yml"
   - "os-{{ ansible_os_family }}.yml"
   - "os-default.yml"

- include: base-debian.yml
  when: ansible_os_family == 'Debian'

- name: Create postgis extension
  become_user: postgres
  postgresql_ext:
    name=postgis
    db={{ postgres__db_name }}
