---

- name: Install Postgis
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=latest
  with_items:
    - postgis
    - postgresql-{{postgres__version}}-postgis-{{postgis__version}}
    - postgresql-{{postgres__version}}-postgis-scripts
  tags:
    - packages
    - debian-base
