---

- debug: msg="Vars path {{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"

- include_vars: "{{ item }}"
  with_first_found:
   - "os-vars-{{ ansible_distribution|lower }}-{{ ansible_distribution_release }}.yml"
   - "os-vars-{{ ansible_distribution|lower }}.yml"
   - "os-vars-{{ ansible_os_family|lower }}.yml"
   - "os-vars-default.yml"

- name: Load OS-Specific Tasks
  include: "{{ item }}"
  with_first_found:
   - "os-{{ ansible_distribution|lower }}-{{ ansible_distribution_release }}.yml"
   - "os-{{ ansible_distribution|lower }}.yml"
   - "os-{{ ansible_os_family|lower }}.yml"
   - "os-default.yml"

- name: Create postgis extension
  become_user: postgres
  postgresql_ext:
    name=postgis
    db={{ postgres__db_name }}

# https://github.com/postgis/docker-postgis/blob/master/9.6-2.5/initdb-postgis.sh
# CREATE EXTENSION IF NOT EXISTS postgis;
# CREATE EXTENSION IF NOT EXISTS postgis_topology;
# CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;
# CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder;