---

- debug: msg="Vars path {{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"

- include_vars: "{{ item }}"
  with_first_found:
   - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
   - "{{ ansible_distribution }}.yml"
   - "{{ ansible_os_family }}.yml"
   - "default.yml"

- include: base-debian.yml
  when: ansible_os_family == 'Debian'

- name: Create postgis extension
  become_user: postgres
  postgresql_ext:
    name=postgis
    db={{ postgres_db_name }}
