---

- name: Install Postgis
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=latest
  with_items:
    - postgis
    - postgresql-{{postgres_version}}-postgis-{{postgis_version}}
    - postgresql-{{postgres_version}}-postgis-scripts
  tags:
    - packages
    - debian-base
