---

- include: debian-base.yml
  when: ansible_os_family == 'Debian'
  tags:
    - postgis

- name: Create postgis extension
  become_user: postgres
  postgresql_ext:
    name=postgis
    db={{ postgres_db_name }}
  tags:
    - postgis
