---

- name: Install Postgis
  apt: name={{ package_to_install }} update_cache={{ update_apt_cache }} state=latest
  with_items:
    - postgis
    - postgresql-{{postgres__version}}-postgis-{{postgis__version}}
    - postgresql-{{postgres__version}}-postgis-scripts
  loop_control:
      loop_var: package_to_install
  tags:
    - packages
    - debian-base
