---
- name: Base states
  hosts: all
  vars:
    - update_apt_cache: yes
  roles:
    - role: base
    - role: unattended
    - role: timezone
    - role: ntp
    - role: nginx
    - role: supervisor
    - role: postfix
    - role: postgres
    - role: postgis
    - role: mysql
    - role: redis
    - role: django
    - role: nrpe
