---
- name: Base states
  hosts: all
  vars:
    - update_apt_cache: yes
  pre_tasks:
    - raw: sudo apt-get install python2.7
  roles:
    - role: nginx
    - role: postfix
    - role: postgres
    - role: postgis
    - role: mysql
    - role: redis
    - role: django
    - role: nrpe
