---
- name: Base states
  hosts: all
  vars:
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
  roles:
    - role: nginx
    - role: postfix
    - role: postgres
    - role: postgis
    - role: mysql
    - role: redis
    - role: django
    - role: nrpe
